export default {
    language: 'Language',
    auto: 'Auto',
    dashboard: 'Dashboard',
    manage: 'SDK Manage',
    repo: 'Repo Manage',
    setting: 'Setting',
    about: 'About',
    configFile: 'Config File',
    getUserHomePathError: 'Failed To Get User\'s Home Directory',
    makeConfigDirError: 'Failed To Make Config Directory',
    makeConfigDirSuccess: 'Success To Make Config Directory',
    touchConfigError: 'Failed To Touch Config File',
    touchConfigSuccess: 'Success To Touch Config File',
    configFileError: 'Config File Error',
    configFileNotExist: 'Config File Not Exist',
    proxy: "Proxy",
    githubProxy: "Github Proxy",
    none: "None",
    custom: "Custom",
    saveConfigError: "Failed To Save Config File",
    saveConfigSuccess: "Success To Save Config File",
    openConfigError: "Failed To Open Config File",
    closeConfigError: "Failed To Close Config File",
    configFileLocked: "Config File Locked",
    deleteConfigLockError: "Failed To Delete Config File Lock",
    getConfigError: "Failed To Get Config File",
    getConfigSuccess: "Success To Get Config File",
    virtualMachine: "Virtual Machine",
}