export default {
    language: '语言',
    auto: '自动',
    dashboard: '控制中心',
    manage: 'SDK 管理',
    repo: '仓库管理',
    setting: '设置',
    about: '关于',
    configFile: '配置文件',
    getUserHomePathError: '获取用户家目录失败',
    makeConfigDirError: '创建配置文件目录失败',
    makeConfigDirSuccess: '创建配置文件目录成功',
    touchConfigError: '创建配置文件失败',
    touchConfigSuccess: '创建配置文件成功',
    configFileError: '配置文件错误',
    configFileNotExist: '配置文件不存在',
    proxy: "代理",
    githubProxy: "Github 加速",
    none: "无",
    custom: "自定义",
    saveConfigError: "配置保存文件失败",
    saveConfigSuccess: "配置保存文件成功",
    openConfigError: "打开配置文件失败",
    closeConfigError: "关闭配置文件失败",
    configFileLocked: "配置文件已被锁定",
    deleteConfigLockError: "删除配置文件读写锁失败",
    getConfigError: "获取配置文件失败",
    getConfigSuccess: "获取配置文件成功",
    virtualMachine: "虚拟机",
}